// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paged.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	paged.proto
	session.proto

It has these top-level messages:
	Paged
	Session
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Paged struct {
	From int32 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *Paged) Reset()                    { *m = Paged{} }
func (m *Paged) String() string            { return proto.CompactTextString(m) }
func (*Paged) ProtoMessage()               {}
func (*Paged) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Paged) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Paged) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Paged)(nil), "mzmico.protobuf.Paged")
}

func init() { proto.RegisterFile("paged.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0x4c, 0x4f,
	0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcf, 0xad, 0xca, 0xcd, 0x4c, 0xce, 0x87,
	0xf0, 0x92, 0x4a, 0xd3, 0x94, 0xf4, 0xb9, 0x58, 0x03, 0x40, 0xf2, 0x42, 0x42, 0x5c, 0x2c, 0x69,
	0x45, 0xf9, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0x36, 0x48, 0xac, 0x38, 0xb3,
	0x2a, 0x55, 0x82, 0x09, 0x22, 0x06, 0x62, 0x3b, 0xc9, 0x44, 0x49, 0xa5, 0x67, 0x96, 0x64, 0x94,
	0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x43, 0x8c, 0xd3, 0x87, 0x19, 0x97, 0xc4, 0x06, 0x66, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x87, 0x16, 0x3c, 0xbf, 0x75, 0x00, 0x00, 0x00,
}
